management:
  endpoints:
    web:
      base-path: /
      exposure:
        include: health
  endpoint:
    health:
      probes:
        enabled: true
      status:
        order: DOWN, OK
        http-mapping:
          OK: 200
          DOWN: 500
      show-details: never
      show-components: never


